# Working with tensor in Eager Mode

- In tensorflow, tensors are multi-dimensional arrays that serve as the basic building blocks for machine learning computations. TensorFlow provides two execution modes:

1. Eager Execution(Default Mode in TF 2.x): Operations are evaluated immediately.
2. Graph Execution (TF 1.x default mode, still available in TF 2.x for performance optimization): Operations are compiled into a computational graph and executed later. 

- Eager execution allows direct interaction with tensors, making debugging and experimentation much easier. 



## Tensor operations in Eager Mode

- When tensorflow runs in eager mode, tensors behave more like NumPy arrays. Operations on tensors return results immediately instead of building a computational graph. 
- Here a + b execute immediately and returns a tensor, rather than constructing a deferred computation graph. 

In [ ]:
import tensorflow as tf

# Ensure eager execution is enabled
tf.config.run_functions_eagerly(True)

# Create tensors
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Element-wise addition
c = a + b
print(c)  # Output: [[ 6  8]
          #          [10 12]]


## Broadcasting in TensorFlow

- Broadcasting allows operations between tensors of different shapes, similar to NumPy´s broadcasting rules. If the shapes are compatible, tensorflow automatically expands the smaller tensor´s dimenstions to match the larger tensor.


In [ ]:
# Example of broadcasting: Broadcasting a Scalar

x = tf.constant([[1.0, 2.0], [3.0, 4.0]])
y = tf.constant(2.0)  # Scalar

z = x * y  # TensorFlow automatically broadcasts y
print(z)

# Output
# [[ 2.  4.]
#  [ 6.  8.]]


In [ ]:
# Example: Broadcasting a Vector to a Matrix
x = tf.constant([[1.0], [2.0], [3.0]])  # Shape (3,1)
y = tf.constant([1.0, 2.0, 3.0])        # Shape (3,)

z = x + y  # Broadcasting applies
print(z)

# Output
# [[2. 3. 4.]
#  [3. 4. 5.]
#  [4. 5. 6.]]


## Operator Overloading

- Tensorflow supports operator overloading, which means you can use standard Python operators (+, -, *, /, @, etc) directly with tensor instead of calling explicit TensorFlow functions. 
- Tensorflow overrides Python´s arithmetic operators to make tensor computations more intuitive. 

In [ ]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Using operator overloading
c = a + b  

# Equivalent to:
c = tf.add(a, b)

print(c)  # Output: [5 7 9]


## NumPy Compatibility
- TensorFlow tensors are compatible with NumPy arrays, making it easy to convert between them. 
- Tensorflow operations work seamlessly with NumPy arrays, making it easier 


In [ ]:
# Convert a Tensor to a NumPy Array
tensor = tf.constant([1.0, 2.0, 3.0])
numpy_array = tensor.numpy()  # Convert to NumPy array
print(type(numpy_array))  # Output: <class 'numpy.ndarray'>


In [ ]:
# Convert a NumPy array to a Tensor

import numpy as np
np_array = np.array([1.0, 2.0, 3.0])
tensor = tf.convert_to_tensor(np_array)  # Convert to TensorFlow tensor
print(type(tensor))  # Output: <class 'tensorflow.python.framework.ops.EagerTensor'>


# Conclusion
- Working with tensors in eager mode in TensorFlow is intuitive and user-friendly. The key benefits include.
1. Immediate Execution: Unlike graph mode, operations execute immediately. 
2. Broadcasting: Tensors follow NumPy-like broadcasting rules.
3. Operator Overloading: Simplifies code by allowing Python operators.
4. NumPy Compatibility: Smooth conversion between tesnros and Numpy arrays. 