# Working with Tensors in Eager Mode

In **TensorFlow**, tensors are multi-dimensional arrays that serve as the fundamental data structure for all machine learning computations. Every input, output, model parameter, and intermediate result is represented as a tensor.

TensorFlow provides two primary execution modes:

1. **Eager Execution** *(Default in TensorFlow 2.x)*  
   Operations are executed immediately, just like standard Python code.

2. **Graph Execution** *(Default in TensorFlow 1.x, optional in TensorFlow 2.x)*  
   Operations are first compiled into a computational graph and then executed. This mode is typically used to improve performance and optimize model deployment.

---

# Eager Execution

**Eager Execution** is the default execution mode in TensorFlow 2.x.

When eager execution is enabled, TensorFlow evaluates every operation immediately and returns the result instantly. This makes TensorFlow behave much more like regular Python and NumPy, greatly simplifying development.

For example:

```python
import tensorflow as tf

x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

z = x + y

print(z)
```

Output:

```text
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
```

Notice that the addition is performed immediately, and the result is available without requiring a separate execution step.

---

# Why Eager Execution?

Before TensorFlow 2.x, developers had to construct a computational graph and explicitly execute it inside a session.

TensorFlow 2.x introduced eager execution as the default because it makes machine learning development much more intuitive.

Advantages include:

- Immediate execution of operations.
- Easier debugging.
- Simple inspection of tensors and variables.
- Natural Python control flow (`if`, `for`, `while`).
- Better integration with Python libraries.
- Faster experimentation and prototyping.

---

# Inspecting Tensors

Since tensors are evaluated immediately, their properties can be inspected directly.

```python
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
```

Check the shape:

```python
tensor.shape
```

Output:

```text
TensorShape([2, 3])
```

Check the data type:

```python
tensor.dtype
```

Output:

```text
tf.int32
```

Check the rank:

```python
tf.rank(tensor)
```

Output:

```text
tf.Tensor(2, shape=(), dtype=int32)
```

---

# Converting a Tensor to a NumPy Array

One of the biggest advantages of eager execution is that tensors can be easily converted to NumPy arrays.

```python
tensor = tf.constant([1, 2, 3])

tensor.numpy()
```

Output:

```python
array([1, 2, 3], dtype=int32)
```

This makes it easy to integrate TensorFlow with other Python scientific libraries.

---

# Tensor Operations

Most mathematical operations work naturally with tensors.

Addition:

```python
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

x + y
```

Output:

```text
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
```

Multiplication:

```python
x * y
```

Output:

```text
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
```

Matrix multiplication:

```python
A = tf.constant([[1, 2],
                 [3, 4]])

B = tf.constant([[5, 6],
                 [7, 8]])

tf.matmul(A, B)
```

Output:

```text
tf.Tensor(
[[19 22]
 [43 50]], shape=(2,2), dtype=int32)
```

---

# Indexing and Slicing

Tensors support indexing and slicing similar to NumPy arrays.

```python
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
```

First row:

```python
tensor[0]
```

Output:

```text
[1 2 3]
```

Second column:

```python
tensor[:, 1]
```

Output:

```text
[2 5]
```

Submatrix:

```python
tensor[:, :2]
```

Output:

```text
[[1 2]
 [4 5]]
```

---

# Automatic Differentiation

Eager execution works seamlessly with **`tf.GradientTape`**, TensorFlow's automatic differentiation system.

This is one of the key features that enables neural networks to learn during training.

Example:

```python
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x ** 2

gradient = tape.gradient(y, x)

print(gradient)
```

Output:

```text
tf.Tensor(6.0, shape=(), dtype=float32)
```

TensorFlow automatically computes the derivative of \(x^2\), which is \(2x\). Since \(x = 3\), the gradient is \(6\).

---

# Eager Execution vs. Graph Execution

| Feature | Eager Execution | Graph Execution |
|---------|-----------------|-----------------|
| Default in TensorFlow 2.x | ✅ | Optional |
| Executes immediately | ✅ | ❌ |
| Easy to debug | ✅ | More difficult |
| Python-like coding | ✅ | Less flexible |
| Performance | Good | Better for large-scale training and deployment |
| Optimized for production | Limited | Excellent |

---

# When is Graph Execution Used?

Although eager execution is ideal for development, TensorFlow can convert Python functions into optimized computational graphs using the **`@tf.function`** decorator.

Example:

```python
@tf.function
def add(x, y):
    return x + y
```

The first time the function is called, TensorFlow traces the operations and builds a computation graph. Subsequent calls reuse this graph, often resulting in faster execution, especially for large models and repetitive computations.

Graph execution is commonly used for:

- Training deep neural networks.
- Large-scale inference.
- Production deployment.
- TPU execution.
- Performance optimization.

---

# Summary

TensorFlow 2.x uses **Eager Execution** by default, allowing operations to execute immediately and making the framework feel like standard Python.

This execution mode provides several benefits:

- Immediate evaluation of tensor operations.
- Easier debugging and experimentation.
- Direct inspection of tensors and variables.
- Simple integration with NumPy and Python code.
- Native support for automatic differentiation with `tf.GradientTape`.

For production environments and maximum performance, TensorFlow can switch to **Graph Execution** using the `@tf.function` decorator, which compiles Python code into an optimized computational graph.

## Tensor operations in Eager Mode

- When tensorflow runs in eager mode, tensors behave more like NumPy arrays. Operations on tensors return results immediately instead of building a computational graph. 
- Here a + b execute immediately and returns a tensor, rather than constructing a deferred computation graph. 

In [ ]:
import tensorflow as tf

# Ensure eager execution is enabled
tf.config.run_functions_eagerly(True)

# Create tensors
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Element-wise addition
c = a + b
print(c)  # Output: [[ 6  8]
          #          [10 12]]


## Broadcasting in TensorFlow

- Broadcasting allows operations between tensors of different shapes, similar to NumPy´s broadcasting rules. If the shapes are compatible, tensorflow automatically expands the smaller tensor´s dimenstions to match the larger tensor.


In [ ]:
# Example of broadcasting: Broadcasting a Scalar

x = tf.constant([[1.0, 2.0], [3.0, 4.0]])
y = tf.constant(2.0)  # Scalar

z = x * y  # TensorFlow automatically broadcasts y
print(z)

# Output
# [[ 2.  4.]
#  [ 6.  8.]]


In [ ]:
# Example: Broadcasting a Vector to a Matrix
x = tf.constant([[1.0], [2.0], [3.0]])  # Shape (3,1)
y = tf.constant([1.0, 2.0, 3.0])        # Shape (3,)

z = x + y  # Broadcasting applies
print(z)

# Output
# [[2. 3. 4.]
#  [3. 4. 5.]
#  [4. 5. 6.]]


## Operator Overloading

- Tensorflow supports operator overloading, which means you can use standard Python operators (+, -, *, /, @, etc) directly with tensor instead of calling explicit TensorFlow functions. 
- Tensorflow overrides Python´s arithmetic operators to make tensor computations more intuitive. 

In [ ]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Using operator overloading
c = a + b  

# Equivalent to:
c = tf.add(a, b)

print(c)  # Output: [5 7 9]


## NumPy Compatibility
- TensorFlow tensors are compatible with NumPy arrays, making it easy to convert between them. 
- Tensorflow operations work seamlessly with NumPy arrays, making it easier 


In [ ]:
# Convert a Tensor to a NumPy Array
tensor = tf.constant([1.0, 2.0, 3.0])
numpy_array = tensor.numpy()  # Convert to NumPy array
print(type(numpy_array))  # Output: <class 'numpy.ndarray'>


In [ ]:
# Convert a NumPy array to a Tensor

import numpy as np
np_array = np.array([1.0, 2.0, 3.0])
tensor = tf.convert_to_tensor(np_array)  # Convert to TensorFlow tensor
print(type(tensor))  # Output: <class 'tensorflow.python.framework.ops.EagerTensor'>


# Conclusion
- Working with tensors in eager mode in TensorFlow is intuitive and user-friendly. The key benefits include.
1. Immediate Execution: Unlike graph mode, operations execute immediately. 
2. Broadcasting: Tensors follow NumPy-like broadcasting rules.
3. Operator Overloading: Simplifies code by allowing Python operators.
4. NumPy Compatibility: Smooth conversion between tesnros and Numpy arrays. 